export { default as Navbar } from '../Components/Navbar'
export { default as Breweries } from '../Brewery/Breweries.jsx'
export { default as Registration } from '../Components/Register'
export { default as Home } from '../Components/Home/Home'
export { default as Login } from '../Components/Login/Login'